`timescale 1ns/1ps
`default_nettype none
// PLEASE READ THIS, IT MAY SAVE YOU SOME TIME AND MONEY, THANK YOU!
// * This file was generated by Quokka FPGA Toolkit.
// * Generated code is your property, do whatever you want with it
// * Place custom code between [BEGIN USER ***] and [END USER ***].
// * CAUTION: All code outside of [USER] scope is subject to regeneration.
// * Bad things happen sometimes in developer's life,
//   it is recommended to use source control management software (e.g. git, bzr etc) to keep your custom code safe'n'sound.
// * Internal structure of code is subject to change.
//   You can use some of signals in custom code, but most likely they will not exist in future (e.g. will get shorter or gone completely)
// * Please send your feedback, comments, improvement ideas etc. to evmuryshkin@gmail.com
// * Visit https://github.com/EvgenyMuryshkin/QuokkaEvaluation to access latest version of playground
//
// DISCLAIMER:
//   Code comes AS-IS, it is your responsibility to make sure it is working as expected
//   no responsibility will be taken for any loss or damage caused by use of Quokka toolkit.
//
// System configuration name is AXISoCQuadCoreModule_TopLevel_cpu3IOGateway_writeAddress, clock frequency is 1Hz, Embedded
// FSM summary
// -- Packages
module AXISoCQuadCoreModule_TopLevel_cpu3IOGateway_writeAddress
(
	// [BEGIN USER PORTS]
	// [END USER PORTS]
	input wire [31:0] iMapAddress,
	input wire [31:0] iOriginalAddress,
	output wire [31:0] oAddress
);
	// [BEGIN USER SIGNALS]
	// [END USER SIGNALS]
	localparam HiSignal = 1'b1;
	localparam LoSignal = 1'b0;
	wire Zero = 1'b0;
	wire One = 1'b1;
	wire true = 1'b1;
	wire false = 1'b0;
	wire signed [6: 0] axiSize = 7'b0100000;
	wire signed [1: 0] originalLowerBits = 2'b00;
	wire AXI4GatewayAddressModule_L31F13T35_Expr = 1'b1;
	wire [31: 0] Inputs_iMapAddress;
	wire [31: 0] Inputs_iOriginalAddress;
	assign Inputs_iMapAddress = iMapAddress;
	assign Inputs_iOriginalAddress = iOriginalAddress;
	assign oAddress = Inputs_iOriginalAddress;
	// [BEGIN USER ARCHITECTURE]
	// [END USER ARCHITECTURE]
endmodule
